NREL/OpenStudio-server

.travis.yml
bin/resources/local.rb

Fixes a typo in kill_processes that I think was leaving child PIDs unkilled in the event of an unsuccessful server startup.  Also, cleans up the PID-killing code for Windows to check if a PID exists before trying to kill because both a failed kill and a kill attempt on a non-existent PID return false.  @nllong or @henryHorsey probably should make sure I didn't break something dumb for Mac.

Fixes and cleanups to PID killing

---

circle.yml
docker-compose.yml
docker/deployment/docker-compose.aws.yml
docker/deployment/scripts/aws_system_init.sh
docker/deployment/scripts/server_provision.sh
docker/deployment/user_variables.json.template

Updated to docker 17.03.0 from 13.0.0.
Changed the deployment protocols to have a private registry which local images are pushed to on boot. This ensures that the swarm doesn't try to resolve image tags against dockerhub.
Fixed issue where only 80 or 8080 resolved the server console. 443 appears to still be an open issue, although it appears to be on the rails configuration side.

Fix several deployment issues

---

docker/deployment/openstudio_server_docker_base.json
docker/deployment/scripts/aws_system_init.sh
docker/deployment/scripts/server_provision.sh
docker/deployment/user_variables.json.template

75% of the storage attached to the server node, plus ~130 GB of EBS, will be available to the osdata volume, which stores all server assets, including zipped results and reports for each datapoint. See https://github.com/NREL/OpenStudio/issues/2605

Fix for 8 GB server zipfile storage limit

---

Dockerfile
ci/travis/setup.sh
docker/R/Dockerfile
docker/R/Rserv.conf
docker/R/install_packages.R
docker/R/ipvs-keepalive.conf
docker/R/rserve-entrypoint.sh
docker/deployment/scripts/aws_system_init.sh
docker/server/ipvs-keepalive.conf
docker/server/rails-entrypoint.sh
server/lib/analysis_library/morris.rb
server/lib/analysis_library/nsga_nrel.rb
server/lib/analysis_library/optim.rb
server/lib/analysis_library/pso.rb
server/lib/analysis_library/rgenoud.rb
server/lib/analysis_library/sobol.rb
server/lib/analysis_library/spea_nrel.rb
server/lib/openstudio_server/version.rb

This patch:
* updates to R from 3.2.3 to 3.4.1
* fixes a networking issue in deployment that caused optimization analyses running longer than 15 minutes to never finish
* adds logging of segmentation faults in the `/mnt/coredumps/` directory
* more aggressively rescues errors in long running analyses

Patch 0 for 2.3.0

---

docker/deployment/docker-compose.aws.yml

https://github.com/moby/moby/issues/26702

Fixing an ipam subnet CIDR /24 that limited network to 252 containers

---

Dockerfile
docker/server/memfix-controller.rb
docker/server/memfix.rb
docker/server/start-server.sh

Implements a process killer in the web container which destroys passenger app workers holding over 500 MBs of RSS.

Rails-memory fix

---

server/Gemfile

Adds the updated version of openstudio-standards gem.  This version includes many bugfixes and also support for CA building assumptions.

Updates openstudio-standards gem to 0.2.0.rc1

---

server/lib/tasks/rubocop.rake

This resolves an issue causing the `--with-test-development` flag to be required for building packages using the `openstudio_meta` command.

Fix install_gems requirement of rspec and rubocop.

---

docker/deployment/scripts/install_openstudio.sh

libwxgtk3.0-0 needs to be installed for OpenStudio 2.4.3.

add new depenendency to install openstudio 2.4.3

---

docker/deployment/scripts/aws_osserver_init.sh

https://github.com/canmet-energy/btap_tasks/issues/58

NRCAN OS-Server[2.5.0] AWS AMI creation: latest tag not found for MongoDB and Redis fix

---

server/app/controllers/analyses_controller.rb
server/config/mongoid.yml
server/spec/factories/project.rb
server/spec/requests/analyses_spec.rb

The map reduce method only returned a cursor for the first 100 objects. If there were more than 100 objects, then it would return a 'cursor not found' error.
The fix performs a second query on the persisted map reduce results to reset the cursor

Fix Cursor Error for analysis_data endpoint

---

Dockerfile
docker-compose.deploy.yml
docker-compose.local.yml
docker-compose.yml
docker/deployment/docker-compose.aws.yml
docker/development/docker-compose.yml
docker/server/rails-entrypoint.sh
docker/server/run-server-tests.sh
docker/server/start-server-dev.sh
docker/server/start-server.sh
docker/server/start-web-background.sh
docker/server/start-workers.sh
docker/server/wait-for-it.sh

The background web containers were starting before mongodb was available.

add wait-for-it to ensure processes start  in the correct order

---

server/app/jobs/dj_jobs/run_simulate_data_point.rb

Currently, when the WFG instantiation / CLI fails to load, no measure_attributes.json file is written, which causes the raise condition which I've removed. This raise leads to the datapoint directory not being zipped and returned to the user through the UI, making it impossible to access the workflow init script log file (which may be needed for debugging) without ssh'ing into the cluster.

Allow failed init scripts to return zip files with logs.

---

docker/R/Dockerfile
docker/R/install_packages.R
server/app/lib/analysis_library/r/cluster.rb

This PR adds in a new R method to check if the R packages are successfully installed. 
The issue was seen when installing a newer DoE.base package that required a new dependency to be installed in the base linux image. The first build of this PR will show a failure, demonstrating that the `install_and_verify` method correctly errors out. The second build will be after the base openstudio-r image has been updated with the change seen here: https://github.com/NREL/docker-openstudio-r/commit/0360dcd95b0fe5696c7b90e95e9ad23d6cba99e4#diff-3254677a7917c6c01f55212f86c57fbfR31 
Note that the 2.7.0 docker images will not work with DoE.base.

Check if R libraries install correctly

---

docker/R/lib/api_create_datapoint.rb
server/app/jobs/dj_jobs/run_simulate_data_point.rb

fix issue https://github.com/NREL/OpenStudio-server/issues/435
tested on bball boxes

Restclient retry

---

docker-compose.deploy.yml
docker/deployment/docker-compose.aws.yml

revert docker swarm config to address https://github.com/NREL/OpenStudio-server/issues/448
must be done in combo with https://github.com/NREL/OpenStudio-PAT/pull/102 
so smaller servers will start up and not have docker resource issues

change limits back to reservations in docker swarm config file

---

ci/appveyor/setup.cmd
docker/R/Dockerfile
server/Gemfile

Roo 2.8.0 released 1/18/2019 drops Ruby 2.2 support.

manage roo and bundler versions

---

.dockerignore
.rubocop.yml
server/Gemfile
server/app/jobs/dj_jobs/run_simulate_data_point.rb
server/app/jobs/resque_jobs/run_simulate_data_point.rb
server/app/models/analysis.rb
server/app/models/data_point.rb
server/spec/factories/compute_node.rb
server/spec/factories/project.rb
server/spec/features/resque_run_simulation_data_point_spec.rb

Fix cancel

---

server/Gemfile

redis gem was trying to install at version 4.1.2 which needs ruby >=2.30 so no go right now.

fix redis to 4.1.0 since 4.1.2 needs ruby 2.3.0

---

docker/server/start-server.sh

We need to remove this.  This zombie's a server cluster when it executes and makes it unrecoverable.  If new issues arise after removing this (so far they havent on NRcan / P+W branches) then those issues should be diagnosed properly and not do something like this.

remove memfix-controller

---

ci/README.md

Looks like CircleCI testing was removed with https://github.com/NREL/OpenStudio-server/commit/b0063811274aa0313ed3202bb6ed811872e4b44c#diff-29944324a3cbf9f4bd0162dfe3975d88, proposing removing this mention of it.

Remove mention of CircleCI

---

server/Gemfile
server/app/jobs/dj_jobs/run_simulate_data_point.rb
server/app/lib/analysis_library/r/lhs.rb
server/app/models/analysis.rb

Dir::Tmpname.make_tmpname is deprecated in Ruby 2.5.0
fixes:
https://github.com/NREL/OpenStudio-server/issues/565

Make tmpname deprecate

---

.travis.yml
appveyor.yml
ci/appveyor/build_package.cmd
ci/appveyor/setup.cmd

This uploads the Windows package to Appveyor's cloud storage for every build. It can be accessed from the Appveyor UI via the "Artifacts" tab for the build.  
For testing, I manually copied the package to S3: https://openstudio-resources.s3.amazonaws.com/pat-dependencies3/OpenStudio-server-20cc98e6f3-win32.tar.gz.  I'll kick off PAT build now.
We will want a final pass to upload these to the correct s3 bucket.
Closes #505

Windows builds

---

.env
CHANGELOG.md
Dockerfile
ci/travis/setup.sh
docker-compose.deploy.yml
docker-compose.local.yml
docker-compose.test.yml
docker-compose.yml
server/Gemfile
server/app/controllers/admin_controller.rb
server/app/lib/openstudio_server/version.rb
server/config/initializers/redis.rb
server/config/mongoid.yml

Updates mongo and redis to use the latest supported versions. Sets a user-defined password for Mongo and Redis.  
Current server mongo::3.4.10
Latest mongo: 4.4.2
Current server redis: 4.0.6
Latest redis: 6.09
This should get updated as well: https://github.com/NREL/OpenStudio-PAT/issues/173

Update mongo and redis

---

server/app/controllers/pages_controller.rb

Fix #641 
Pretty simple fix for this. I captured the debug log on mongo to verify the server accepted this optional arg and it did (see allowDiskUse in capture) so this should fix the memory exceed limit, at least according to the mongo documentation.  
conn10","msg":"Slow query","attr":{"type":"command","ns":"os_docker.data_points","command":{"aggregate":"data_points","pipeline":[{"$match":               {"analysis_id":"6b8b090f-d6c8-4751-b485-c293546efa4a"}},{"$group":{"_id":{"analysis_id":"$analysis_id","status":"$status"},"count":{"$sum":1}}}],"cursor":{},"**allowDiskUse**":true,"$db":"os_docker","lsid":{"id":{"$uuid":"2315132a-8720-4c1c-849e-       82c040c35009"}}},"planSummary":"COLLSCAN","keysExamined":0,"docsExamined":328,"cursorExhausted":true,"numYields":0,"nreturned":1,"queryHas …

pass in allow_disk_usage to mongo

---

server/Gemfile

Should address some of the Trivy issues. The `Go` and `cgi` may be container specific. Not sure we can update `bundler` and `rexml` without updating the entire OpenStudio-extension world.

update rails for security patches

---

server/Gemfile

Update UO dependency with new release of URBANopt that supports HPXML 1.5.1 (OpenStudio 3.5.1)

update UO for hpxml 151

---

server/app/jobs/dj_jobs/run_simulate_data_point.rb
server/app/jobs/dj_jobs/urban_opt.rb
server/app/lib/analysis_library/schema/osa.json
server/app/lib/utility/oss.rb
server/app/models/analysis.rb

Related https://github.com/NREL/OpenStudio-PAT/pull/249
This PR attempts to simply the process of using ruby gems vs using an `initialization.sh` script that modifies the existing Gemfile on the worker nodes. The current way to run a workflow using custom gems looks something like this:
1 ) A user includes a worker initialization script (e.g https://github.com/NREL/OpenStudio-server/blob/develop/doc/initialization_scripts/set_gem_version.sh) that changes the contents of the existing Gemfile on the worker node (e.g. /opt/openstudio/server/Gemfile) with the desired gems.  Bundler then installs these gems to /opt/openstudio/server/gems
2 ) A datapoint runs on the worker node and uses these gems if this value is set - https://github.com/NREL/OpenStudio-server/blob/develop/server/config/environ …

Using bundled ruby gems with analysis runs

---

.github/workflows/security-scan.yml
Dockerfile
ci/github-actions/setup.sh
docker-compose.deploy.yml
docker-compose.local.yml
docker-compose.test.yml
docker-compose.yml
local_setup_scripts/nuke.sh
local_setup_scripts/rebuild_sr.sh
local_setup_scripts/win64/nuke.ps1
local_setup_scripts/win64/nuke.sh
local_setup_scripts/win64/rebuild_sr.sh
local_setup_scripts/win64/rebuild_sr_no_rm.sh
server/Gemfile
spec/tests/openstudio_meta_spec.rb

bump mongo to 6.0.7

---

server/app/models/analysis.rb
server/app/models/data_point.rb
server/app/models/job.rb
server/app/models/measure.rb
server/app/models/pareto.rb
server/app/models/project.rb
server/app/models/variable.rb
server/spec/features/docker_stack_algo_spec.rb
server/spec/features/docker_stack_test_apis_spec.rb
server/spec/features/docker_stack_urbanopt_algo_spec.rb

https://github.com/NREL/OpenStudio-server/issues/712

Mongo indexes

---

server/Gemfile

Mongoid paperclip now uses kt-paperclip, this should now work.

Update mongoid and use release of mongoid-paperclip
