NREL/OpenStudio-server

CHANGELOG.md
server/lib/openstudio_server/version.rb
vagrant/chef/roles/openstudio.rb

Os 1.12.1.7d1634ec2e

---

server/app/models/variable.rb
server/lib/analysis/baseline_perturbation.rb
server/lib/analysis/deoptim.rb
server/lib/analysis/diag.rb
server/lib/analysis/doe.rb
server/lib/analysis/lhs.rb
server/lib/analysis/morris.rb
server/lib/analysis/nsga_nrel.rb
server/lib/analysis/optim.rb
server/lib/analysis/preflight.rb
server/lib/analysis/pso.rb
server/lib/analysis/r/diag.rb
server/lib/analysis/r/lhs.rb
server/lib/analysis/rgenoud.rb
server/lib/analysis/sequential_search.rb
server/lib/analysis/sobol.rb
server/lib/analysis/spea_nrel.rb

adding @r r session to pivot variable.rb so it can make the sequence if necessary.

adding integer_sequence as a distribution type

---

CHANGELOG.md
server/lib/analysis/diag.rb
server/lib/openstudio_server/version.rb

diagonal now works with pivots and no variables

Diag 0 vars

---

server/Gemfile
server/app/workers/run_simulate_data_point.rb

This updates dockerize branch to use the latest osw branch of workflow gem, this pull request should be synchronized with https://github.com/NREL/OpenStudio-workflow-gem/pull/56
@nllong @henryHorsey

Dockerize osw

---

bin/resources/local.rb
bin/resources/local/dj_server_command
bin/resources/local/dj_worker_command
bin/resources/local/mongo_command
bin/resources/local/rails_command

In addition, stdout and stderr are being piped to files now using the ruby's Open3 stdlib functionality. This should fix remaining issues around open pipes to invoking process.

Re-re-re-jigger process management for start_local to allow for cleaner stop_local

---

server/Gemfile
server/app/workers/run_simulate_data_point.rb
server/spec/models/run_simulation_data_point_spec.rb

connect up sdp_log_file again
https://www.pivotaltracker.com/story/show/132706161

add in log to data point

---

server/app/models/analysis.rb
server/app/models/data_point.rb
server/app/models/preflight_image.rb
server/app/models/result_file.rb
server/config/config.yml
server/config/initializers/default_config.rb
server/lib/analysis_library/batch_run.rb
server/lib/analysis_library/diag.rb

if running local environment then make sure to set ENV var for the project directory (OS_SERVER_PROJECT_PATH)
```
local:
<<: *defaults
os_server_host_url: <%= ENV['OS_SERVER_HOST_URL'] %>
os_server_project_path: <%= ENV['OS_SERVER_PROJECT_PATH'] %>
rails_log_path: <%= ENV['OS_SERVER_LOG_PATH'] %>
```

Dockerize paths

---

bin/openstudio_meta
bin/resources/local.rb

Tested with process-explorer extensively.

Identify and Kill all Windows Ruby Sub-Processes

---

bin/openstudio_meta
bin/resources/local.rb

This uses native windows utilities to manage the destruction of processes on windows, and additionally ensures that a) in case of a local_configuration.json file existing in the project directory the server will not start and that b) in case of a failed start the local_configuration.json file will be deleted.

Taskkill implementation for windows

---

bin/resources/local.rb
server/Gemfile
server/app/controllers/data_points_controller.rb

Moving this into the deployment branch.

Moving to Ruby 2.2.4

---

bin/resources/local.rb
server/app/controllers/admin_controller.rb
server/config/config.yml
server/config/initializers/default_config.rb

add tmp directory config
fix db dump name

fix db dump

---

server/Gemfile

PR'ing this to make sure that the Circle tests still pass.

Bumping Analysis gem version to support DA weather files and seed models

---

Dockerfile
docker/server/run-server-tests.sh

needed to upgrade geckodriver.

Fix selenium

---

Dockerfile
server/lib/openstudio_server/version.rb

Updating to OpenStudio 2.0.5 and EnergyPlus 8.7 (fixes PR #151)

---

Dockerfile
server/Gemfile

Moving WFG to 1.2.0 and OS version 2.0.5 SHA to a2578157f.

Bumping WFG and OS version.

---

Dockerfile
ci/appveyor/setup.cmd

Attempting 2.0.5 public release deb package test.

Bringing dockerize up to 2.0.5 release package.

---

Dockerfile
docker/R/Dockerfile
docker/R/rserve-entrypoint.sh
docker/server/rails-entrypoint.sh
server/app/models/preflight_image.rb
server/app/models/result_file.rb
server/app/models/variable.rb

In a separate branch, as things could go very wrong in the process of these fixes.

Permissions related fixes

---

Dockerfile
docker/server/rails-entrypoint.sh
server/app/controllers/admin_controller.rb

Restore will be a slightly different cup of tea.

Mongo Dump fix

---

docker/deployment/docker-compose.aws.yml
docker/deployment/openstudio_server_docker_base.json
docker/deployment/scripts/server_provision.sh

As so many things are, this is painfully easy in retrospect.

Fix to ensure local docker containers are used in swarm mode on AWS

---

docker/deployment/docker-compose.aws.yml
docker/deployment/openstudio_server_docker_base.json
docker/deployment/scripts/server_provision.sh
server/lib/openstudio_server/version.rb

Fixes hard size limitation on the server. The new limit will be 75% of ephemeral storage, plus ~135GB of attached EBS storage.

2.1.1 patch 1 release

---

server/lib/openstudio_server/version.rb

Dear tests, please be less finicky this time. Thanks, Ry

Merge down 2.1.2 to master

---

docker/deployment/scripts/aws_system_init.sh

Fixing docker version update.

---

Dockerfile
server/lib/openstudio_server/version.rb

Reverts NREL/OpenStudio-server#202

Revert "Updating to OpenStudio 2.2.2"

---

Dockerfile
ci/travis/setup.sh
docker/R/Dockerfile
docker/R/Rserv.conf
docker/R/ipvs-keepalive.conf
docker/deployment/scripts/aws_system_init.sh
docker/server/ipvs-keepalive.conf
server/lib/analysis_library/morris.rb
server/lib/analysis_library/nsga_nrel.rb
server/lib/analysis_library/optim.rb
server/lib/analysis_library/pso.rb
server/lib/analysis_library/rgenoud.rb
server/lib/analysis_library/sobol.rb
server/lib/analysis_library/spea_nrel.rb

Fix for timeout in IPVS Rserve connection leading to orphaned EOF repsonse to the analysis job queue object

Optimization Infinite Hang Fix

---

docker/R/Dockerfile
docker/R/install_packages.R
server/lib/openstudio_server/version.rb

tested on 24
ran 2 rgenoud runs fully on same box.
server still responsive

update R and Rserve version

---

docker/development/Dockerfile-dev
docker/development/docker-compose.yml
docker/server/start-server-dev.sh
server/Gemfile
server/config/config.yml
server/config/environments/docker-dev.rb
server/config/mongoid.yml
server/config/secrets.yml

Ability to run dev environment within docker.

Add Docker Dev Environment

---

ci/travis/setup.sh

Merge as soon as travis is passing again.

Attempting to pin mongo version to avoid XCode 8.3.2

---

server/Gemfile
server/app/views/admin/index.html.erb
server/config/routes.rb

* add resque dashboard
* add button on admin page
This includes PR #233 as well.

add resque dashboard

---

Dockerfile
circle.yml
server/lib/openstudio_server/version.rb

Reenabling Circle for all builds until Travis migration complete.

Upgrade OpenStudio to 2.4.1

---

ci/appveyor/setup.cmd
ci/appveyor/test.ps1

Change OpenStudio install path for AppVeyor

---

bin/openstudio_meta

Update bundler installed by openstudio_meta to 1.14.4

---

circle.yml
docker-compose.test.yml
docker-compose.yml
docker/deployment/scripts/circle_deployment.sh

* cleanup build scripts to not include test branch. 
* cleanup docker-compose files to be consistent.

240 270 docker hub

---

.travis.yml
ci/travis/setup.sh
ci/travis/test.sh

Resurrect Ubuntu unit testing

---

ci/gitlab/README.md
ci/gitlab/build_deploy_ami.py

Updates to the AMI automation script and documentation to support custom AMIs.
Waiting for 2.3.2 to re-test release automation.

One-off AMI generation

---

docker/server/nginx.conf

https://github.com/NREL/OpenStudio-server/issues/310

bump datapoint limit to 1000MB

---

.travis.yml
appveyor.yml
ci/appveyor/install-windows.qs
ci/appveyor/setup.cmd
ci/travis/install-mac.qs
ci/travis/setup.sh
ci/travis/test.sh
docker/deployment/scripts/install_openstudio.sh

The install.qs script that was being downloaded from NREL/OpenStudio changed from underneath us. Put the install.qs script into this repo.

Osx openstudio not loading

---

ci/gitlab/README.md
ci/gitlab/build_deploy_ami.py

Create custom AMI's with GitHub ref Gemfiles

---

.gitignore
Dockerfile
circle.yml
docker/deployment/scripts/circle_deployment.sh

Moves the deploy build into the test section. Docker-compose is not accessible in the deployment section anymore for some reason.

cleanup deploy script

---

server/lib/analysis_library/gather_results.rb

https://github.com/canmet-energy/btap_tasks/issues/60

 Added bundle install and bundle exec ruby 2.4.3

---

server/app/lib/analysis_library/gather_results.rb

https://github.com/canmet-energy/btap_tasks/issues/60

 Added bundle install and bundle exec ruby 2.5.0

---

server/app/jobs/dj_jobs/run_simulate_data_point.rb

Fix the old reference to `run_file` and the make log path unique for each datapoint.

Script fix

---

server/app/jobs/dj_jobs/run_simulate_data_point.rb
server/spec/features/dj_run_simulation_data_point_spec.rb

Oscli output

---

ci/travis/setup.sh
server/app/controllers/admin_controller.rb
server/app/jobs/dj_jobs/run_simulate_data_point.rb
server/app/lib/utility/oss.rb
server/spec/requests/pages_spec.rb

Fixes #418 
Fixes #421 (just passing path with quotes)

function to encapsulate the platform- and config- specific logic for Oscli calls

---

.travis.yml
ci/appveyor/setup.cmd
docker/deployment/scripts/deploy_docker.sh
server/app/lib/openstudio_server/version.rb

only allowed with extension in specified format.  
directions here: https://github.com/NREL/OpenStudio-server/wiki/Developer-Guide:-Building-and-Publishing-Docker-images

support publishing custom docker image

---

server/app/jobs/dj_jobs/run_simulate_data_point.rb
server/app/models/analysis.rb
server/app/models/compute_node.rb

temporary relief of issue https://github.com/NREL/OpenStudio-server/issues/460
until timeouts become user configurable

bump up timeouts until they can be made user selectable

---

CHANGELOG.md
lib/release_instructions.md

still need to update Dockerfile when nrel/openstudio:2.8.0 is available

2.8.0 Release draft

---

server/Gemfile

rubocop-rspec 1.32.0

---

CHANGELOG.md
LICENSE
lib/update_license.rb
server/Gemfile
server/app/lib/openstudio_server/version.rb

Prepare 2.8.1

---

server/app/controllers/admin_controller.rb
server/app/jobs/dj_jobs/run_simulate_data_point.rb
server/app/lib/utility/oss.rb
server/app/views/admin/index.html.erb

do not output version extension

---

bin/resources/remote.rb
doc/initialization_scripts/set_gem_version.sh
server/Gemfile
server/app/jobs/dj_jobs/run_simulate_data_point.rb

bumping up timeouts to at least an hour.  this is needed with ppl sending larger zips around on production clusters.

bump up timeouts to at least an hour

---

bin/resources/remote.rb
doc/initialization_scripts/set_gem_version.sh
docker/R/Dockerfile
server/Gemfile
server/app/jobs/dj_jobs/run_simulate_data_point.rb

bump up timeouts to at least an hour.  needed for larger zips which are becoming more frequent
https://github.com/NREL/OpenStudio-server/issues/366

bump up timeouts to at least 1 hr in dev3

---

local_setup_scripts/README.md
server/app/jobs/dj_jobs/run_simulate_data_point.rb
server/app/models/analysis.rb

same as https://github.com/NREL/OpenStudio-server/pull/531
but for develop3 branch

add cli args to dev3 branch

---

server/app/jobs/dj_jobs/run_simulate_data_point.rb
server/app/models/analysis.rb
server/spec/files/test_model/test_model.json

Timeout args

---

server/app/jobs/dj_jobs/run_simulate_data_point.rb
server/app/models/analysis.rb
server/spec/files/test_model/test_model.json

add bad values to test_model.json which should get changed to defaults for testing
https://github.com/NREL/OpenStudio-server/issues/460
https://github.com/NREL/OpenStudio-server/issues/366

add timeouts as user args

---

local_setup_scripts/win64/docker-compose.yml
local_setup_scripts/win64/docker_logs.sh
local_setup_scripts/win64/docker_logs2.sh
local_setup_scripts/win64/nuke.ps1
local_setup_scripts/win64/nuke.sh
local_setup_scripts/win64/rebuild_sr.sh
local_setup_scripts/win64/rebuild_sr_no_rm.sh
local_setup_scripts/win64/redeploy.sh

fix typos in existing scripts. add windows versions from fmu branch

add windows versions of local_setup_scripts

---

server/Gemfile

2.9.x LTS Patch Gems

---

bin/openstudio_meta

Updating method to set GEM_HOME and GEM_PATH

update setting gem_home and gem_path

---

docker/R/lib/create_and_run_datapoint.R
docker/R/lib/create_and_run_datapoint_uniquegroups.R
docker/deployment/docker-compose.aws.yml

add sleep(5) to create_and_run_datapoint

endpoint dnsrr needs docker-compose version >3.2

---

.github/workflows/openstudio-server-tests.yml
appveyor.yml
ci/appveyor/setup.cmd
ci/github-actions/install_openstudio.sh
ci/github-actions/setup.sh
server/app/lib/openstudio_server/version.rb

Update to 3.2.1 SDK

---

server/app/jobs/dj_jobs/run_simulate_data_point.rb

Fixes https://github.com/NREL/OpenStudio-PAT/issues/186

fix in.osm not downloadable

---

.github/workflows/openstudio-server-tests.yml

Results will show up in the security tab:
https://github.com/NREL/OpenStudio-server/security/code-scanning?page=2&query=branch%3Aadd-trivy+is%3Aopen+severity%3Aerror

Add docker container scanning using Trivy

---

.github/workflows/openstudio-server-tests.yml
Dockerfile
appveyor.yml
ci/appveyor/setup.cmd
ci/github-actions/install_openstudio.sh
ci/github-actions/setup.sh
server/Gemfile
server/app/controllers/pages_controller.rb
server/app/lib/openstudio_server/version.rb

OpenStudio v3.3.0

---

.github/workflows/openstudio-server-tests.yml
Dockerfile
appveyor.yml
ci/appveyor/setup.cmd
ci/github-actions/install_openstudio.sh
ci/github-actions/setup.sh
server/Gemfile
server/app/controllers/pages_controller.rb
server/app/lib/openstudio_server/version.rb
server/spec/features/openstudio_algo_spec.rb

Update to OS SDK 3.3.0

---

.github/workflows/openstudio-server-tests.yml
Dockerfile
appveyor.yml
ci/appveyor/setup.cmd
ci/github-actions/install_openstudio.sh
ci/github-actions/setup.sh
server/Gemfile
server/app/lib/openstudio_server/version.rb

Update to OpenStudio 3.4.0-rc1

OpenStudio 3.4.0 rc1

---

.github/workflows/openstudio-server-tests.yml
Dockerfile
appveyor.yml
ci/appveyor/setup.cmd
ci/github-actions/install_openstudio.sh
ci/github-actions/setup.sh
server/Gemfile
server/app/lib/openstudio_server/version.rb
server/spec/features/openstudio_algo_spec.rb

Update to 3.4.0-rc2

---

Dockerfile
server/app/controllers/admin_controller.rb

https://github.com/NREL/OpenStudio-server/issues/648

show CLI version on admin page

---

.github/workflows/openstudio-server-tests.yml
Dockerfile
appveyor.yml
ci/appveyor/setup.cmd
ci/github-actions/install_openstudio.sh
ci/github-actions/setup.sh
server/app/lib/openstudio_server/version.rb

update to use 3.4.0 official

---

docker/R/lib/morris.R
docker/R/lib/sobol.R
server/app/lib/analysis_library/sobol.rb
server/spec/features/docker_stack_algo_spec.rb
server/spec/files/SEB_Sobol_2013.json

this fixes https://github.com/NREL/OpenStudio-server/issues/667 for morris and sobol

Sobol and morris fix

---

.github/workflows/openstudio-server-tests.yml
Dockerfile
appveyor.yml
ci/appveyor/setup.cmd
ci/github-actions/install_openstudio.sh
ci/github-actions/setup.sh
local_setup_scripts/rebuild_sr.sh
local_setup_scripts/win64/rebuild_sr.sh
local_setup_scripts/win64/rebuild_sr_no_rm.sh
server/app/lib/openstudio_server/version.rb

updates for 3.5.0 sdk official

updates for 3.5.0 sdk official

---

.github/workflows/openstudio-server-tests.yml
CHANGELOG.md
Dockerfile
appveyor.yml
ci/appveyor/setup.cmd
ci/github-actions/install_openstudio.sh
ci/github-actions/setup.sh
local_setup_scripts/rebuild_sr.sh
local_setup_scripts/win64/rebuild_sr.sh
local_setup_scripts/win64/rebuild_sr_no_rm.sh
server/app/lib/openstudio_server/version.rb

Update to SDK 3.5.0

---

server/Gemfile
server/app/lib/analysis_library/fast99.rb
server/app/lib/analysis_library/morris.rb
server/app/lib/analysis_library/sobol.rb

https://github.com/NREL/OpenStudio-server/issues/689
if display_name_short not defined, there can be issues, so check for it

Short name

---

.github/workflows/openstudio-server-tests.yml
.github/workflows/security-scan.yml
Dockerfile
appveyor.yml
ci/appveyor/setup.cmd
ci/github-actions/install_openstudio.sh
ci/github-actions/setup.sh
local_setup_scripts/rebuild_sr.sh
local_setup_scripts/win64/rebuild_sr.sh
local_setup_scripts/win64/rebuild_sr_no_rm.sh
server/app/lib/openstudio_server/version.rb

updates for 3.6.1

---

.github/workflows/security-scan.yml

Fixing the security scan that is filling up disk space.

Fix actions

---

server/Gemfile

https://github.com/NREL/OpenStudio-server/issues/721

analysis-gem 1.3.5
